Repository DH-React-Next-Project/racket-talk, pull requests merged in 2025-05, with the labels that each got.

#3 Style: 화면 최대너비 제한 설정 및 커스텀 테마 색상 추가
  src/app/layout.tsx
  src/app/page.tsx
  src/styles/globals.css
  src/styles/tailwind.css
Labels: design

#7 Feat: 회원가입 기능 구현
  package.json
  prisma/schema.prisma
  src/_components/.gitkeep
  src/_components/home/LandingBtn.tsx
  src/app/api/join/route.ts
  src/app/api/login/route.ts
  src/app/api/user/join/route.ts
  src/app/join/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/assets/home/Logo.svg
  src/assets/join/logo-without-text.svg
  src/utils/prismaClient.ts
  tsconfig.json
  yarn.lock
Labels: feat

#11 Feat: 로그인 기능 구현
  next.config.ts
  src/app/api/user/login/route.ts
  src/app/chat/page.tsx
  src/app/join/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/assets/root/logo.svg
  src/middleware.ts
Labels: feat

#13 Feat: 하단탭 구현
  src/_components/layouts/BottomTab.tsx
  src/app/layout.tsx
  src/app/map/page.tsx
  src/assets/layouts/chat-icon.svg
  src/assets/layouts/map-icon.svg
  src/assets/layouts/my-icon.svg
  src/assets/layouts/selected-chat-icon.svg
  src/assets/layouts/selected-map-icon.svg
  src/assets/layouts/selected-my-icon.svg
Labels: feat

#16 Chore: 로그인 및 회원가입 후 리다이렉트 로직 추가
  prisma/schema.prisma
  src/app/chat/page.tsx
  src/app/join/page.tsx
  src/app/login/page.tsx
Labels: chore

#19 Feat : 홈 화면
  package-lock.json
  package.json
  prisma/schema.prisma
  public/img/map-marker.png
  src/_components/court/Modal.tsx
  src/_components/court/ToggleFavorite.tsx
  src/app/api/court/[court_id]/route.ts
  src/app/api/court/route.ts
  src/app/map/page.tsx
  src/assets/courts/map-marker.svg
  src/assets/courts/phone.svg
  src/assets/courts/selected-favorite.svg
  src/assets/courts/unselected-favorite.svg
  yarn.lock
Labels: feat

#20 Feat: 채팅
  next.config.ts
  package.json
  prisma/schema.prisma
  src/_components/chat/ChatRoom.tsx
  src/_components/chat/Messages.tsx
  src/_components/chat/OutModal.tsx
  src/_components/layouts/Header.tsx
  src/app/api/chat/history/route.ts
  src/app/api/chat/join-room-list/route.ts
  src/app/api/chat/leave-room/route.ts
  src/app/api/ws/route.ts
  src/app/chat-room/[room-id]/page.tsx
  src/app/chat/page.tsx
  src/assets/chat/back-icon.svg
  src/assets/chat/chat-out.svg
  src/assets/chat/logo-ball.svg
  src/assets/chat/sent-message.svg
  src/assets/layouts/logo.svg
  src/styles/tailwind.css
  src/types/chat.d.ts
  yarn.lock
Labels: feat

#22 Feature/#6
  .gitignore
  .idea/.gitignore
  src/app/api/court-detail/[court_id]/route.ts
  src/app/court-detail/[court_id]/page.tsx
  src/app/map/page.tsx
  src/assets/courts/clock.svg
  src/assets/courts/phone-black.svg
  src/assets/courts/point.svg
Labels: feat

#26 Feat: 코트 채팅방 조회
  prisma/schema.prisma
  src/_components/chat/CourtChatRoom.tsx
  src/_components/layouts/Header.tsx
  src/app/api/chat/room-list/route.ts
  src/app/api/court-detail/[court_id]/route.ts
  src/app/chat-room/[room-id]/page.tsx
  src/app/chat/page.tsx
  src/app/court-chat-list/page.tsx
  src/app/court-detail/[court_id]/page.tsx
  src/app/map/page.tsx
  src/types/chat.d.ts
Labels: feat
